### ISSUE TITLE
Track MappedDiagnosticsLogicalContext

### ISSUE THREAD

**Issue by di97mni** [Microsoft/ApplicationInsights-dotnet-logging#19]
If you need to have custom context variables that will flow across async points, you can use NLog to have the MappedDiagnosticsLogicalContext class and the ${mdlc} layout render.

It would be great if this would be sent to AI as well. The same as for [properties](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/master/src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs#L139).

[More info](http://www.bfcamara.com/post/67752957760/nlog-how-to-include-custom-context-variables-in)
Note. This is for NLog.Contrib but NLog 4.2 now has this as well

**Comment by abaranch** [comment]
MappedDiagnosticsLogicalContext does not allow to get all items in the context. You can get only each item by name.
1. Usually properties from MappedDiagnosticsLogicalContext are included in the layout that we would start supporting from the next version: #20 
2. You can write TelemetryInitializer and include properties from MappedDiagnosticsLogicalContext  because you know property names you use (that you can do already with existing version). Read [this](http://apmtips.com/blog/2014/12/01/telemetry-initializers/)
