### ISSUE TITLE
Compatibility of Microsoft.ApplicationInsights.TraceListener Version 2.4.0 with Microsoft.ApplicationInsights Version 2.6.4

### ISSUE THREAD

**Issue by alexsab1** [Microsoft/ApplicationInsights-dotnet-logging#200]
According to the nuget page [Microsoft.ApplicationInsights.TraceListener Version 2.4.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights.TraceListener/2.4.0) is compatible with Microsoft.ApplicationInsights (>= 2.4.0).

Therefore when I updated Microsoft.ApplicationInsights 2.4.0 to the latest version in Visual Studio 2017, my Microsoft.ApplicationInsights.TraceListener version 2.4.0 remained without an update.

When I ran the application I found out that Microsoft.ApplicationInsights.TraceListener Version 2.4.0 does not work with Microsoft.ApplicationInsights 2.6.4 anymore.

I then updated Microsoft.ApplicationInsights.TraceListener to version 2.6.4.

While I see that I should have matched the latest version for Microsoft.ApplicationInsights.TraceListener to version 2.6.4 in the first place, is this also an issues with the website that advertises compatibility when in fact in does not work?

Thank you!

**Comment by SergeyKanzhelev** [comment]
@MS-TimothyMothra can you comment on this?

@alexsab1 please expand on what you mean by "does not work with Microsoft.ApplicationInsights 2.6.4 anymore"? Does it not compile or breaks in runtime?

**Comment by MS-TimothyMothra** [comment]
Hi @alexsab1, I'm glad to hear you were able to resolve your issue with a manual upgrade.
I'm very sorry to hear that didn't work for you out of the box, thank you for bringing that to our attention.

If you remember what the error was that you encountered, I would be very interested in reviewing that.

There should not have been any breaking changes in our Microsoft.ApplicationInsights library between versions 2.4.0 and 2.6.4, which is why we let TraceListener work with versions greater than or equal to a specific version. We will certainly review that decision!
