### ISSUE TITLE
ApplicationInsightsTraceListener does not respect Flush

### ISSUE THREAD

**Issue by markanewman** [Microsoft/ApplicationInsights-dotnet-logging#67]
When calling Trace.Flush(), some of the last messages may be lost. Per [this](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-windows-desktop), TelemetryClient.Flush needs to be called to make sure the last batch is sent.

**Comment by kavanj** [comment]
A similar issue exists in `ApplicationInsightsAppender` (Log4NetAppender).
`ApplicationInsightsAppender` doesn't override `AppenderSkeleton.Flush()`, so calling `Flush` just hits [AppenderSkeleton.Flush()](https://github.com/apache/log4net/blob/trunk/src/Appender/AppenderSkeleton.cs#L792).

I haven't experimented with `ApplicationInsightsTarget` (NLogTarget), but I'd expect the same issue to exist there, since there doesn't appear to be anything calling `TelemetryClient.Flush()`

**Comment by markanewman** [comment]
I am not familiar with NLog, but I looked for `AppenderSkeleton.Flush()` before I put in my PR and was unable to find it. The [version](https://www.nuget.org/packages/log4net/2.0.5) that is referenced doesn't implement the `IFlushable` interface in the latest [code](http://svn.apache.org/viewvc/logging/log4net/trunk/src/Appender/AppenderSkeleton.cs?view=markup). To my eye, this seems to be the issue with #68.
