### ISSUE TITLE
EventSourceListener NuGet package overrides user settings in AI.config file

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/ApplicationInsights-dotnet-logging#88]
Repro steps (not completely verified, just something I noticed when doing app building)

1. Create a .NET console app, add Microsoft.ApplicationInsights.EventSourceListener package, version < latest
2. Modify the list of captured EventSources in ApplicationInsights.config
3. Upgrade EventSourceListener to latest version (currently 2.4.0-beta1)

Expected: the list of captured EventSources is not affected
Actual: the list of captured EventSources is reset to the default (1 artificial EventSource)

This might also be an issue for the EtwCollector package (haven't verified that)

**Comment by SergeyKanzhelev** [comment]
NuGet will install the previous package first and then update the new one. There is no indication that the uninstall is actually an "update". So this behavior is by design.

One of idea we are thinking about is to detach "structure" config defining the chains and initializers and custom overrides.

So I think this problem should be moved to the `-dotnet` repo as general design improvement.

**Comment by karolz-ms** [comment]
Aha, did not realize that, thanks for clarification.

Will open an issue in `-dotnet` portal

**Comment by karolz-ms** [comment]
Opened https://github.com/Microsoft/ApplicationInsights-dotnet/issues/555 to track this
